[tool.ruff]
# Enable Pyflakes (F) and pycodestyle (E) codes by default.
# Also enable isort (I) for import sorting.
select = ["E", "F", "I"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Same as Black.
line-length = 88

[tool.ruff.isort]
known-first-party = ["db_config"]

[tool.pyright]
include = ["."]
exclude = ["**/node_modules", "**/__pycache__"]
pythonVersion = "3.9"
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false

[tool.basedpyright]
# If the user uses basedpyright (Zed's default)
typeCheckingMode = "basic"
